export const CONTRACT_FRACTIONALIZE_ADDRESS = process.env
  .NEXT_PUBLIC_CONTRACT_FRACTIONALIZE_ADDRESS! as `0x${string}`;
export const CONTRACT_NFT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_NFT_ADDRESS! as `0x${string}`;
